export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Game } from './Game'
export { default as Games } from './Games'
export { default as GameHistory } from './GameHistory'